import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import DrawingCanvas from "../components/DrawingCanvas";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Canvas React</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-5xl bg-gray-800 w-full mx-auto">
        <div className="flex flex-col items-center">
          <h1 className="">Canvas Drawing App</h1>
          <DrawingCanvas />
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
